#############################################################################
# Makefile for building: cdm_install
# Generated by qmake (2.01a) (Qt 4.8.7) on: mar. janv. 30 14:26:38 2018
# Project:  cdm_install.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -o Makefile cdm_install.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qwt-6-1-2-qwt-pro \
		sub-qwtplot3d-qwtplot3d-pro \
		sub-cdmlib-cdmlib-pro \
		sub-cdm-cdm-pro

qwt-6.1.2/$(MAKEFILE).qwt: 
	@$(CHK_DIR_EXISTS) qwt-6.1.2/ || $(MKDIR) qwt-6.1.2/ 
	cd qwt-6.1.2/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/qwt-6.1.2/qwt.pro -o $(MAKEFILE).qwt
sub-qwt-6-1-2-qwt-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qwt-6.1.2/ || $(MKDIR) qwt-6.1.2/ 
	cd qwt-6.1.2/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/qwt-6.1.2/qwt.pro -o $(MAKEFILE).qwt
sub-qwt-6-1-2-qwt-pro: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt
sub-qwt-6-1-2-qwt-pro-make_default-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt 
sub-qwt-6-1-2-qwt-pro-make_default: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt 
sub-qwt-6-1-2-qwt-pro-make_first-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt first
sub-qwt-6-1-2-qwt-pro-make_first: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt first
sub-qwt-6-1-2-qwt-pro-all-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt all
sub-qwt-6-1-2-qwt-pro-all: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt all
sub-qwt-6-1-2-qwt-pro-clean-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt clean
sub-qwt-6-1-2-qwt-pro-clean: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt clean
sub-qwt-6-1-2-qwt-pro-distclean-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt distclean
sub-qwt-6-1-2-qwt-pro-distclean: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt distclean
sub-qwt-6-1-2-qwt-pro-install_subtargets-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt install
sub-qwt-6-1-2-qwt-pro-install_subtargets: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt install
sub-qwt-6-1-2-qwt-pro-uninstall_subtargets-ordered: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt uninstall
sub-qwt-6-1-2-qwt-pro-uninstall_subtargets: qwt-6.1.2/$(MAKEFILE).qwt FORCE
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt uninstall
qwtplot3d/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qwtplot3d/ || $(MKDIR) qwtplot3d/ 
	cd qwtplot3d/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/qwtplot3d/qwtplot3d.pro -o $(MAKEFILE)
sub-qwtplot3d-qwtplot3d-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qwtplot3d/ || $(MKDIR) qwtplot3d/ 
	cd qwtplot3d/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/qwtplot3d/qwtplot3d.pro -o $(MAKEFILE)
sub-qwtplot3d-qwtplot3d-pro: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE)
sub-qwtplot3d-qwtplot3d-pro-make_default-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-make_default-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) 
sub-qwtplot3d-qwtplot3d-pro-make_default: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) 
sub-qwtplot3d-qwtplot3d-pro-make_first-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-make_first-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) first
sub-qwtplot3d-qwtplot3d-pro-make_first: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) first
sub-qwtplot3d-qwtplot3d-pro-all-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-all-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) all
sub-qwtplot3d-qwtplot3d-pro-all: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) all
sub-qwtplot3d-qwtplot3d-pro-clean-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-clean-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) clean
sub-qwtplot3d-qwtplot3d-pro-clean: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) clean
sub-qwtplot3d-qwtplot3d-pro-distclean-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-distclean-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qwtplot3d-qwtplot3d-pro-distclean: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qwtplot3d-qwtplot3d-pro-install_subtargets-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-install_subtargets-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) install
sub-qwtplot3d-qwtplot3d-pro-install_subtargets: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) install
sub-qwtplot3d-qwtplot3d-pro-uninstall_subtargets-ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-uninstall_subtargets-ordered  FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qwtplot3d-qwtplot3d-pro-uninstall_subtargets: qwtplot3d/$(MAKEFILE) FORCE
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) uninstall
cdmlib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cdmlib/ || $(MKDIR) cdmlib/ 
	cd cdmlib/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/cdmlib/cdmlib.pro -o $(MAKEFILE)
sub-cdmlib-cdmlib-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cdmlib/ || $(MKDIR) cdmlib/ 
	cd cdmlib/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/cdmlib/cdmlib.pro -o $(MAKEFILE)
sub-cdmlib-cdmlib-pro: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE)
sub-cdmlib-cdmlib-pro-make_default-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-make_default-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) 
sub-cdmlib-cdmlib-pro-make_default: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) 
sub-cdmlib-cdmlib-pro-make_first-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-make_first-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) first
sub-cdmlib-cdmlib-pro-make_first: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) first
sub-cdmlib-cdmlib-pro-all-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-all-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) all
sub-cdmlib-cdmlib-pro-all: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) all
sub-cdmlib-cdmlib-pro-clean-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-clean-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) clean
sub-cdmlib-cdmlib-pro-clean: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) clean
sub-cdmlib-cdmlib-pro-distclean-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-distclean-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cdmlib-cdmlib-pro-distclean: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cdmlib-cdmlib-pro-install_subtargets-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-install_subtargets-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) install
sub-cdmlib-cdmlib-pro-install_subtargets: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) install
sub-cdmlib-cdmlib-pro-uninstall_subtargets-ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-uninstall_subtargets-ordered  FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-cdmlib-cdmlib-pro-uninstall_subtargets: cdmlib/$(MAKEFILE) FORCE
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) uninstall
cdm/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cdm/ || $(MKDIR) cdm/ 
	cd cdm/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/cdm/cdm.pro -o $(MAKEFILE)
sub-cdm-cdm-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cdm/ || $(MKDIR) cdm/ 
	cd cdm/ && $(QMAKE) /home/pchaumet/cdm/libre/cdm-0.3.7/cdm/cdm.pro -o $(MAKEFILE)
sub-cdm-cdm-pro: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE)
sub-cdm-cdm-pro-make_default-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-make_default-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) 
sub-cdm-cdm-pro-make_default: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) 
sub-cdm-cdm-pro-make_first-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-make_first-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) first
sub-cdm-cdm-pro-make_first: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) first
sub-cdm-cdm-pro-all-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-all-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) all
sub-cdm-cdm-pro-all: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) all
sub-cdm-cdm-pro-clean-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-clean-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) clean
sub-cdm-cdm-pro-clean: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) clean
sub-cdm-cdm-pro-distclean-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-distclean-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cdm-cdm-pro-distclean: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cdm-cdm-pro-install_subtargets-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-install_subtargets-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) install
sub-cdm-cdm-pro-install_subtargets: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) install
sub-cdm-cdm-pro-uninstall_subtargets-ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-uninstall_subtargets-ordered  FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-cdm-cdm-pro-uninstall_subtargets: cdm/$(MAKEFILE) FORCE
	cd cdm/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: cdm_install.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile cdm_install.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile cdm_install.pro

qmake_all: sub-qwt-6-1-2-qwt-pro-qmake_all sub-qwtplot3d-qwtplot3d-pro-qmake_all sub-cdmlib-cdmlib-pro-qmake_all sub-cdm-cdm-pro-qmake_all FORCE

make_default: sub-qwt-6-1-2-qwt-pro-make_default-ordered sub-qwtplot3d-qwtplot3d-pro-make_default-ordered sub-cdmlib-cdmlib-pro-make_default-ordered sub-cdm-cdm-pro-make_default-ordered FORCE
make_first: sub-qwt-6-1-2-qwt-pro-make_first-ordered sub-qwtplot3d-qwtplot3d-pro-make_first-ordered sub-cdmlib-cdmlib-pro-make_first-ordered sub-cdm-cdm-pro-make_first-ordered FORCE
all: sub-qwt-6-1-2-qwt-pro-all-ordered sub-qwtplot3d-qwtplot3d-pro-all-ordered sub-cdmlib-cdmlib-pro-all-ordered sub-cdm-cdm-pro-all-ordered FORCE
clean: sub-qwt-6-1-2-qwt-pro-clean-ordered sub-qwtplot3d-qwtplot3d-pro-clean-ordered sub-cdmlib-cdmlib-pro-clean-ordered sub-cdm-cdm-pro-clean-ordered FORCE
distclean: sub-qwt-6-1-2-qwt-pro-distclean-ordered sub-qwtplot3d-qwtplot3d-pro-distclean-ordered sub-cdmlib-cdmlib-pro-distclean-ordered sub-cdm-cdm-pro-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qwt-6-1-2-qwt-pro-install_subtargets-ordered sub-qwtplot3d-qwtplot3d-pro-install_subtargets-ordered sub-cdmlib-cdmlib-pro-install_subtargets-ordered sub-cdm-cdm-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-qwt-6-1-2-qwt-pro-uninstall_subtargets-ordered sub-qwtplot3d-qwtplot3d-pro-uninstall_subtargets-ordered sub-cdmlib-cdmlib-pro-uninstall_subtargets-ordered sub-cdm-cdm-pro-uninstall_subtargets-ordered FORCE

sub-qwt-6-1-2-qwt-pro-check_ordered: qwt-6.1.2/$(MAKEFILE).qwt
	cd qwt-6.1.2/ && $(MAKE) -f $(MAKEFILE).qwt check
sub-qwtplot3d-qwtplot3d-pro-check_ordered: qwtplot3d/$(MAKEFILE) sub-qwt-6-1-2-qwt-pro-check_ordered 
	cd qwtplot3d/ && $(MAKE) -f $(MAKEFILE) check
sub-cdmlib-cdmlib-pro-check_ordered: cdmlib/$(MAKEFILE) sub-qwtplot3d-qwtplot3d-pro-check_ordered 
	cd cdmlib/ && $(MAKE) -f $(MAKEFILE) check
sub-cdm-cdm-pro-check_ordered: cdm/$(MAKEFILE) sub-cdmlib-cdmlib-pro-check_ordered 
	cd cdm/ && $(MAKE) -f $(MAKEFILE) check
check: sub-qwt-6-1-2-qwt-pro-check_ordered sub-qwtplot3d-qwtplot3d-pro-check_ordered sub-cdmlib-cdmlib-pro-check_ordered sub-cdm-cdm-pro-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

